### ISSUE TITLE
Output of transformer decoder

### ISSUE THREAD

**Issue by sudo-Boris** [wjun0830/CGDETR#14]
Hi! Thank you for the great work!

There are a lot of different components to this architecture. It's quite impressive!

I was somewhat wondering how the transformer decoder works. In the paper, you don't say anything about how it works. (At least I couldn't find much)

How many windows can it predict? For QVH, there can be multiple relevant windows for one query and video.

In the paper, Figure 2, you show 3 query tokens. What exactly do they mean?
Can you predict a variable number of relevant windows or only a fixed number?
Is the objective generative?

**Comment by wjun0830** [comment]
Thank you for your interest.

Regarding the number of predictions, multiple windows can be predicted. This is because Hungarian matching is implemented span-wise rather than batch-wise.

Additionally, the number of query tokens shown in the figure is for illustration purposes only and does not carry any special meaning. 

The objective for moment prediction is regression.

Thank you
